Install and Import Ultralytics library

In [1]:
!pip install ultralytics
from ultralytics import YOLO

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 612.4/612.4 kB 27.4 MB/s eta 0:00:00


Set the working directory

In [2]:
import os
HOME = os.getcwd()
print(HOME)

/content


Install dataset

In [3]:
!mkdir {HOME}/datasets
%cd {HOME}/datasets



!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="Ztrni2ePZEBOO7ZJZMUk")
project = rf.workspace("varun-yvyoy").project("invoice-processing-nl2cz")
dataset = project.version(1).download("yolov8")



/content/datasets
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 5.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 17.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 7.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.8/67.8 kB 8.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 6.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 8.1 MB/s eta 0:00:00
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9657 sha256=82835e4c355b85a9015b4954401db4fd8bfdc006d1f80a12d0ef2fb34bf576b7
  Stored in directory: /root/.cache/pip/wheels/8b/f1/7f/5c94f0a7a505ca1c81cd1d9208ae2064675d97582078e6c769
Successfully built wget
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 3.1.0
    

loading Roboflow workspace...
loading Roboflow project...
Dependency ultralytics<=8.0.20 is required but found version=8.0.123, to fix: `pip install ultralytics<=8.0.20`


Extracting Dataset Version Zip to Invoice-Processing-1 in yolov8:: 100%|██████████| 512/512 [00:00<00:00, 2567.99it/s]


Install Tesseract Dependencies

In [4]:
!pip install pytesseract
!apt install tesseract-ocr
!apt install tesseract-ocr-eng


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  tesseract-ocr-eng tesseract-ocr-osd
The following NEW packages will be installed:
  tesseract-ocr tesseract-ocr-eng tesseract-ocr-osd
0 upgraded, 3 newly installed, 0 to remove and 13 not upgraded.
Need to get 4,850 kB of archives.
After this operation, 16.3 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 tesseract-ocr-eng all 1:4.00~git30-7274cfa-1 [1,598 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/universe amd64 tesseract-ocr-osd all 1:4.00~git30-7274cfa-1 [2,990 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/universe amd64 tesseract-ocr amd64 4.1.1-2build2 [262 kB]
Fetched 4,850 kB in 0s (19.0 MB/s)
Selecting previously unselected package tesseract-ocr-eng.
(Reading database ..

Install Paddle-OCR dependencies

In [5]:
!pip install paddlepaddle
!pip install paddlepaddle paddleocr
!paddleocr --download_lang en


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.9/124.9 MB 8.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.4/75.4 kB 8.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.2/383.2 kB 41.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 10.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 8.1 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 445.9/445.9 kB 23.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 813.9/813.9 kB 5.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 299.2/299.2 kB 31.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 88.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 83.4 MB/s eta 0:00:0

usage: paddleocr
       [-h]
       [--use_gpu USE_GPU]
       [--use_xpu USE_XPU]
       [--use_npu USE_NPU]
       [--ir_optim IR_OPTIM]
       [--use_tensorrt USE_TENSORRT]
       [--min_subgraph_size MIN_SUBGRAPH_SIZE]
       [--precision PRECISION]
       [--gpu_mem GPU_MEM]
       [--image_dir IMAGE_DIR]
       [--page_num PAGE_NUM]
       [--det_algorithm DET_ALGORITHM]
       [--det_model_dir DET_MODEL_DIR]
       [--det_limit_side_len DET_LIMIT_SIDE_LEN]
       [--det_limit_type DET_LIMIT_TYPE]
       [--det_box_type DET_BOX_TYPE]
       [--det_db_thresh DET_DB_THRESH]
       [--det_db_box_thresh DET_DB_BOX_THRESH]
       [--det_db_unclip_ratio DET_DB_UNCLIP_RATIO]
       [--max_batch_size MAX_BATCH_SIZE]
       [--use_dilation USE_DILATION]
       [--det_db_score_mode DET_DB_SCORE_MODE]
       [--det_east_score_thresh DET_EAST_SCORE_THRESH]
       [--det_east_cover_thresh DET_EAST_COVER_THRESH]
       [--det_east_nms_thresh DET_EAST_NMS_THRESH]
       [--det_sast_score_thresh

Crop the regions of interest and perform OCR on them using Tesseract and Paddle-OCR

In [7]:
import cv2
import os
import datetime
import pytesseract
from paddleocr import PaddleOCR

# Path to the folder containing the images
image_folder = "/content/datasets/Invoice-Processing-1/test/images"

# Create a unique timestamp for the output directory
timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
output_directory = f"/content/final_folder_{timestamp}/"
os.makedirs(output_directory, exist_ok=True)

# Initialize the YOLO model
model = YOLO('/content/best.pt')

# Initialize Tesseract
pytesseract.pytesseract.tesseract_cmd = r'/usr/bin/tesseract'  # Update with the path to your Tesseract installation

# Initialize PaddleOCR
ocr_paddle = PaddleOCR()

# Iterate over the images in the folder
for image_file in os.listdir(image_folder):
    if image_file.endswith((".jpg", ".png", ".jpeg")):
        image_path = os.path.join(image_folder, image_file)

        # Create a new directory for each image
        image_output_directory = os.path.join(output_directory, f"{image_file}_output/")
        os.makedirs(image_output_directory, exist_ok=True)

        # Load the image
        img = cv2.imread(image_path)

        # Perform object detection
        results = model.predict(img)

        # Iterate over the detection results
        for result in results:
            boxes = result.boxes.cpu().numpy()
            for i, box in enumerate(boxes):
                name = result.names[int(box.cls)]
                r = box.xyxy[0].astype(int)
                print(name)
                print(r)
                crop = img[r[1]:r[3], r[0]:r[2]]
                cv2.imwrite(os.path.join(image_output_directory, str(name) + ".jpg"), crop)

        # Perform OCR with Tesseract on the image
        image_files = [f for f in os.listdir(image_output_directory) if f.endswith((".jpg", ".png", ".jpeg"))]
        ocr_tesseract_results = []

        for image_file in image_files:
            image_path = os.path.join(image_output_directory, image_file)
            image = cv2.imread(image_path)
            ocr_text = pytesseract.image_to_string(image)
            ocr_tesseract_results.append(f"File: {image_file}\nOCR Text (Tesseract):\n{ocr_text}\n")

        # Save the Tesseract OCR results to a text file
        tesseract_output_file = os.path.join(image_output_directory, "ocr_results_tesseract.txt")
        with open(tesseract_output_file, "w") as file:
            file.write("\n\n".join(ocr_tesseract_results))

        # Perform OCR with PaddleOCR on the image
        ocr_paddle_results = []

        for image_file in image_files:
            image_path = os.path.join(image_output_directory, image_file)
            image = cv2.imread(image_path)
            ocr_result = ocr_paddle.ocr(image)
            ocr_text = '\n'.join([word_info[1][0] for line in ocr_result for word_info in line])
            ocr_paddle_results.append(f"File: {image_file}\nOCR Text (PaddleOCR):\n{ocr_text}\n")

        # Save the PaddleOCR results to a text file
        paddle_output_file = os.path.join(image_output_directory, "ocr_results_paddle.txt")
        with open(paddle_output_file, "w") as file:
            file.write("\n\n".join(ocr_paddle_results))

print("OCR process completed!")


download https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar to /root/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer/ch_PP-OCRv3_det_infer.tar


100%|██████████| 3.83M/3.83M [00:15<00:00, 245kiB/s] 


download https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_rec_infer.tar to /root/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer/ch_PP-OCRv3_rec_infer.tar


100%|██████████| 11.9M/11.9M [00:17<00:00, 668kiB/s] 


download https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar to /root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer/ch_ppocr_mobile_v2.0_cls_infer.tar


100%|██████████| 2.19M/2.19M [00:14<00:00, 154kiB/s]

[2023/06/27 13:05:52] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/root/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/root/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='/usr/local



0: 800x800 1 address, 1 billto, 2 companys, 1 payment_info, 1 table, 1 total, 1121.4ms
Speed: 14.0ms preprocess, 1121.4ms inference, 37.6ms postprocess per image at shape (1, 3, 800, 800)


table
[ 66 278 557 405]
company
[194  43 457 110]
payment_info
[ 63 465 370 535]
total
[404 415 569 480]
billto
[ 68 175 314 239]
address
[ 67 175 321 240]
company
[ 74 246 280 270]
[2023/06/27 13:06:00] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:00] ppocr DEBUG: dt_boxes num : 6, elapse : 0.04806828498840332
[2023/06/27 13:06:01] ppocr DEBUG: rec_res num  : 6, elapse : 0.735569953918457
[2023/06/27 13:06:01] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:01] ppocr DEBUG: dt_boxes num : 20, elapse : 0.10614204406738281
[2023/06/27 13:06:03] ppocr DEBUG: rec_res num  : 20, elapse : 2.3588526248931885
[2023/06/27 13:06:03] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:03] ppocr DEBUG: dt_boxes 


0: 800x800 3 billtos, 1 date, 2 invoice_numbers, 1 shipto, 1 table, 2 totals, 789.9ms
Speed: 5.9ms preprocess, 789.9ms inference, 1.0ms postprocess per image at shape (1, 3, 800, 800)


table
[213 241 594 357]
total
[376 422 569 503]
date
[228  86 398 104]
billto
[222 141 462 195]
invoice_number
[218  40 402  85]
total
[225 197 431 225]
invoice_number
[226  71 404  87]
billto
[ 43 136 173 222]
shipto
[226 138 291 222]
billto
[ 43 537 197 605]
[2023/06/27 13:06:08] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:08] ppocr DEBUG: dt_boxes num : 1, elapse : 0.018654823303222656
[2023/06/27 13:06:08] ppocr DEBUG: rec_res num  : 1, elapse : 0.14359402656555176
[2023/06/27 13:06:08] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:08] ppocr DEBUG: dt_boxes num : 16, elapse : 0.05679798126220703
[2023/06/27 13:06:10] ppocr DEBUG: rec_res num  : 16, elapse : 1.4753093719482422
[2023/06/27 13:06:10] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will n


0: 800x800 1 address, 1 company, 1 invoice_number, 1 table, 1 total, 824.2ms
Speed: 7.1ms preprocess, 824.2ms inference, 1.0ms postprocess per image at shape (1, 3, 800, 800)


total
[383 393 540 460]
address
[184 112 507 131]
company
[191  56 482 102]
invoice_number
[367 157 484 173]
table
[ 31 221 555 468]
[2023/06/27 13:06:14] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:14] ppocr DEBUG: dt_boxes num : 4, elapse : 0.034871816635131836
[2023/06/27 13:06:14] ppocr DEBUG: rec_res num  : 4, elapse : 0.50128173828125
[2023/06/27 13:06:14] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:14] ppocr DEBUG: dt_boxes num : 13, elapse : 0.17796754837036133
[2023/06/27 13:06:16] ppocr DEBUG: rec_res num  : 13, elapse : 1.5636639595031738
[2023/06/27 13:06:16] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:16] ppocr DEBUG: dt_boxes num : 1, elapse : 0.02813243865966797
[2023/06/27


0: 800x800 1 billto, 1 date, 1 invoice_number, 1 payment_info, 1 table, 1 total, 1260.1ms
Speed: 6.7ms preprocess, 1260.1ms inference, 1.1ms postprocess per image at shape (1, 3, 800, 800)


date
[531 127 609 148]
total
[438 400 614 473]
table
[240 161 602 329]
invoice_number
[238 112 362 149]
payment_info
[452 511 639 600]
billto
[483  46 609 104]
[2023/06/27 13:06:19] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:19] ppocr DEBUG: dt_boxes num : 6, elapse : 0.023105621337890625
[2023/06/27 13:06:19] ppocr DEBUG: rec_res num  : 6, elapse : 0.4334428310394287
[2023/06/27 13:06:19] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:20] ppocr DEBUG: dt_boxes num : 15, elapse : 0.06358098983764648
[2023/06/27 13:06:21] ppocr DEBUG: rec_res num  : 15, elapse : 1.3502895832061768
[2023/06/27 13:06:21] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:21] ppocr DEBUG: dt_boxes num : 4, elapse : 0.


0: 800x800 1 address, 1 billto, 2 companys, 1 date, 1 invoice_number, 1 shipto, 2 tables, 1 total, 810.5ms
Speed: 6.4ms preprocess, 810.5ms inference, 1.1ms postprocess per image at shape (1, 3, 800, 800)


billto
[ 39 137 156 196]
shipto
[216 138 347 197]
address
[ 38  89 154 116]
date
[383 185 599 207]
invoice_number
[388 139 605 156]
total
[392 365 607 401]
company
[ 42  64 146  83]
table
[  8 267 610 359]
table
[ 28 214 606 363]
company
[ 41 220 247 259]
[2023/06/27 13:06:25] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:25] ppocr DEBUG: dt_boxes num : 4, elapse : 0.01825690269470215
[2023/06/27 13:06:25] ppocr DEBUG: rec_res num  : 4, elapse : 0.2821991443634033
[2023/06/27 13:06:25] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:25] ppocr DEBUG: dt_boxes num : 18, elapse : 0.09105682373046875
[2023/06/27 13:06:27] ppocr DEBUG: rec_res num  : 18, elapse : 1.5439724922180176
[2023/06/27 13:06:27] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be u


0: 800x800 1 address, 1 billto, 1 company, 1 date, 1 invoice_number, 1 payment_info, 1 table, 1 total, 1302.0ms
Speed: 6.3ms preprocess, 1302.0ms inference, 1.4ms postprocess per image at shape (1, 3, 800, 800)


billto
[ 70 184 332 259]
company
[112  98 251 139]
table
[ 65 270 630 440]
payment_info
[363 202 600 257]
invoice_number
[387 122 534 147]
total
[415 440 602 502]
date
[434 104 609 121]
address
[134 618 452 636]
[2023/06/27 13:06:33] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:33] ppocr DEBUG: dt_boxes num : 6, elapse : 0.04232311248779297
[2023/06/27 13:06:33] ppocr DEBUG: rec_res num  : 6, elapse : 0.534998893737793
[2023/06/27 13:06:33] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:33] ppocr DEBUG: dt_boxes num : 24, elapse : 0.08616161346435547
[2023/06/27 13:06:35] ppocr DEBUG: rec_res num  : 24, elapse : 1.8599560260772705
[2023/06/27 13:06:35] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13


0: 800x800 1 address, 2 billtos, 2 companys, 2 dates, 2 invoice_numbers, 1 shipto, 1 table, 2 totals, 784.8ms
Speed: 5.9ms preprocess, 784.8ms inference, 1.0ms postprocess per image at shape (1, 3, 800, 800)


shipto
[235 167 372 228]
billto
[ 39 167 157 228]
invoice_number
[400 101 601 119]
total
[402 336 603 374]
invoice_number
[395  96 608 117]
date
[398 149 603 171]
table
[ 38 232 565 328]
billto
[ 38 100 160 162]
company
[ 43  23 251  44]
company
[ 42 523 220 547]
total
[406 337 605 414]
address
[ 38 100 159 161]
date
[392 120 605 139]
[2023/06/27 13:06:40] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:40] ppocr DEBUG: dt_boxes num : 5, elapse : 0.026489734649658203
[2023/06/27 13:06:40] ppocr DEBUG: rec_res num  : 5, elapse : 0.34749412536621094
[2023/06/27 13:06:40] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:40] ppocr DEBUG: dt_boxes num : 17, elapse : 0.058702945709228516
[2023/06/27 13:06:41] ppocr DEBUG: rec_res num  : 17, elapse : 1.3849475383758545
[2023/06/27 13:06:41] ppocr WARNIN


0: 800x800 2 billtos, 1 company, 1 date, 2 invoice_numbers, 1 shipto, 1 table, 1 total, 1300.7ms
Speed: 6.4ms preprocess, 1300.7ms inference, 1.4ms postprocess per image at shape (1, 3, 800, 800)


table
[ 60 306 585 477]
billto
[ 44 141 249 220]
company
[113  36 541  92]
invoice_number
[483 144 595 189]
invoice_number
[507 250 592 295]
shipto
[ 51 226 230 294]
billto
[ 50 226 231 295]
date
[500 251 595 291]
total
[ 62 456 588 486]
[2023/06/27 13:06:48] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:48] ppocr DEBUG: dt_boxes num : 2, elapse : 0.0376582145690918
[2023/06/27 13:06:48] ppocr DEBUG: rec_res num  : 2, elapse : 0.18955469131469727
[2023/06/27 13:06:48] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:48] ppocr DEBUG: dt_boxes num : 21, elapse : 0.0818932056427002
[2023/06/27 13:06:49] ppocr DEBUG: rec_res num  : 21, elapse : 1.4728808403015137
[2023/06/27 13:06:49] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forw


0: 800x800 2 companys, 1 invoice_number, 1 table, 779.1ms
Speed: 6.1ms preprocess, 779.1ms inference, 1.1ms postprocess per image at shape (1, 3, 800, 800)


company
[ 37  28 244  53]
invoice_number
[ 38  55 129  72]
table
[ 32 247 618 354]
company
[486  56 602  71]
[2023/06/27 13:06:53] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:53] ppocr DEBUG: dt_boxes num : 17, elapse : 0.05876302719116211
[2023/06/27 13:06:55] ppocr DEBUG: rec_res num  : 17, elapse : 1.7181930541992188
[2023/06/27 13:06:55] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:55] ppocr DEBUG: dt_boxes num : 1, elapse : 0.0200192928314209
[2023/06/27 13:06:55] ppocr DEBUG: rec_res num  : 1, elapse : 0.07414793968200684
[2023/06/27 13:06:55] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:55] ppocr DEBUG: dt_boxes num : 1, elapse : 0.013831138610839844
[2023/06/27 13:06:55] ppocr DEBUG


0: 800x800 2 addresss, 1 company, 1 invoice_number, 1 payment_info, 1 table, 1 total, 784.7ms
Speed: 7.4ms preprocess, 784.7ms inference, 1.0ms postprocess per image at shape (1, 3, 800, 800)


table
[ 36 215 585 409]
company
[148  45 563 119]
total
[351 421 580 488]
invoice_number
[401 164 594 202]
address
[ 60 567 187 625]
payment_info
[ 52 415 309 503]
address
[460 568 579 622]
[2023/06/27 13:06:57] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:57] ppocr DEBUG: dt_boxes num : 6, elapse : 0.02331233024597168
[2023/06/27 13:06:57] ppocr DEBUG: rec_res num  : 6, elapse : 0.4103703498840332
[2023/06/27 13:06:57] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:06:58] ppocr DEBUG: dt_boxes num : 19, elapse : 0.11308813095092773
[2023/06/27 13:07:00] ppocr DEBUG: rec_res num  : 19, elapse : 2.274869680404663
[2023/06/27 13:07:00] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:07:00] ppocr DEBUG: d


0: 800x800 2 addresss, 1 company, 1 date, 1 invoice_number, 1 payment_info, 1 table, 2 totals, 985.9ms
Speed: 7.0ms preprocess, 985.9ms inference, 1.0ms postprocess per image at shape (1, 3, 800, 800)


invoice_number
[223 192 409 216]
table
[ 64 233 577 359]
company
[ 62  76 348 152]
payment_info
[ 63 374 233 468]
date
[273 382 361 434]
address
[456  77 589 141]
total
[425 381 548 453]
address
[  0  78  78 147]
total
[402 376 579 463]
[2023/06/27 13:07:04] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:07:04] ppocr DEBUG: dt_boxes num : 2, elapse : 0.025972843170166016
[2023/06/27 13:07:04] ppocr DEBUG: rec_res num  : 2, elapse : 0.14099454879760742
[2023/06/27 13:07:04] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/06/27 13:07:04] ppocr DEBUG: dt_boxes num : 24, elapse : 0.07416653633117676
[2023/06/27 13:07:06] ppocr DEBUG: rec_res num  : 24, elapse : 1.9502573013305664
[2023/06/27 13:07:06] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the fo